services:
  postgres:
      image: postgres:latest
      container_name: wellwave-postgres-prod
      restart: always
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DATABASE}
        POSTGRES_USER: ${POSTGRES_USER}
      ports:
        - "${DB_PORT:-5432}:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data

  backend:
    image: wellwave-backend-prod
    container_name: wellwave-backend
    restart: always
    build:
      context: ./wellwave-backend
      dockerfile: Dockerfile.prod
      # args:
      #   API_PORT: ${API_PORT}
    environment:
      NODE_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - "${API_PORT:-3000}:3000"
    depends_on:
      - postgres

  website:
    image: wellwave-website-prod
    container_name: wellwave-website-prod
    restart: always
    build:
      context: ./wellwave-website
      dockerfile: Dockerfile.prod
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    depends_on:
      - backend

  nginx:
    image: nginx:apline
    container_name: wellwave-nginx
    restart: always
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - backend
      - website
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      # - ./nginx/certbot/conf:/etc/letsencrypt
      # - ./nginx/certbot/www:/var/www/certbot

volumes:
  postgres-data:
    driver: local